spring:
  application:
    name: shop-management

  datasource:
    url: jdbc:postgresql://localhost:5432/shop_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/shop_db
    user: postgres
    password: password
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: samgitonga66@gmail.com
    password: qzho ypkj cimh jjxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "b2df428b9929d3ace7c6e7f49e9a5e5f478c25d6f83f1c4e5b8f1e5f4a9d8b77"
  access:
    expiration: 90000000
  refresh:
    expiration: 604800000

  profiles:
    active: docker

server:
  port: 8080

mpesa:
    consumer.key: 74YJ4AmD6GnOC0enMiQlc5q5jcc45YGgmCkSOYEF3t7npAOP
    consumer.secret: hnsd3u3oywEkAv54ZCXGyZVywN6UjK9i3XSJvxqmq2k48vL1MAi34nXwisZ715Al
    business.shortcode: "174379"
    passkey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919

    callback.url: "https://5cfcdceef99e.ngrok-free.app/api/v1/payments/mpesa/callback"

    auth.url: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"
    stk.push.url: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"