spring:
  application:
    name: shop-management

  datasource:
    url: jdbc:postgresql://localhost:5432/shop_management
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/shop_management
    user: postgres
    password: password

  mail:
    host: smtp.gmail.com
    port: 587
    username: samgitonga66@gmail.com
    password: qzho ypkj cimh jjxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "b2df428b9929d3ace7c6e7f49e9a5e5f478c25d6f83f1c4e5b8f1e5f4a9d8b77"
  access:
    expiration: 90000000
  refresh:
    expiration: 604800000

profiles:
  active: docker

server:
  port: 8080
